### ISSUE TITLE
Error when importing api-reference package in Next.js app

### ISSUE THREAD

**Issue by tkalejaiye** [scalar/scalar#495] opened 2023-11-16 20:04 UTC
### Expected Behavior

I've included the ApiReference component in the home page of my Next.js app (using app router) and expected to see the API reference at localhost:3000

### Actual Behavior

Getting  `TypeError: Cannot redefine property: ApiClientModal`

<img width="847" alt="Screen Shot 2023-11-16 at 14 04 09" src="https://github.com/scalar/scalar/assets/3721667/1390c9c9-bdc2-469f-9e90-6b2372c4ea45">

### Reproduction steps

```bash
1. Create a new Next.js app using `npx create-next-app@latest` and select all defaults
2. Run `npm install @scalar/api-reference` and `npm i veaury`
3. Replace code in app/page.js with the following:


import { ApiReference as VueComponent } from "@scalar/api-reference"
import { applyVueInReact } from "veaury"

const ApiReference = applyVueInReact(VueComponent)

export default function Home() {
  return (
    <>
    {/* Explanation: https://github.com/devilwjp/veaury#typescript-jsx-types-conflict-caused-by-vue-and-react-at-the-same-time
      // @ts-ignore */}
    <ApiReference configuration={{isEditable: true}} />
    </>
    
  )
}
```
4. Run `npm run dev` and go to localhost:3000 in browser
```


### Version

1.1.2

### What browsers are you seeing the problem on?

_No response_

**Comment by hanspagel** [comment] 2023-11-20 11:11
Thanks so much for providing an easy to follow reproduction! Can reproduce it, will try to fix it.

**Comment by hanspagel** [comment] 2023-11-20 11:59
Hm … I can’t really find a solution. This doesn’t work as expected in a Next.js/Webpack environment:

```ts
export { default as ApiClientModal } from './components/ApiClientModal.vue'
export { default as ApiReference } from './components/ApiReference.vue'
export { default as ApiReferenceLayout } from './components/ApiReferenceLayout.vue'
export { default as ApiReferenceBase } from './components/ApiReferenceBase.vue'
export { default as Sidebar } from './components/Sidebar.vue'
export { default as RenderedReference } from './components/Content/Content.vue'
export { default as DarkModeToggle } from './components/DarkModeToggle.vue'
export { default as SearchModal } from './components/SearchModal.vue'
```

**Comment by marclave** [comment] 2023-11-26 00:18
@hanspagel @tkalejaiye 

so i was investigating and seems like this error is relevant, i downgraded to 14.0.1 and added 
```
'use client'
```

to the top of the file, however now it renders the Scalar API References for about half a second then disappears!

**Comment by marclave** [comment] 2023-11-26 00:19
```
'use client'
import { ApiReference as VueComponent } from "@scalar/api-reference"
import { applyVueInReact } from "veaury"


const ApiReference = applyVueInReact(VueComponent)
const configuration = { proxy: 'https://api.scalar.com/request-proxy', spec: { url: 'https://petstore.swagger.io/v2/swagger.json' }, isEditable: true }

console.log('hi')

export default function Home() {
  return (
    <>
      <h1>hi hello</h1>
      <div>
      {/* Explanation: https://github.com/devilwjp/veaury#typescript-jsx-types-conflict-caused-by-vue-and-react-at-the-same-time
      // @ts-ignore */}
        <ApiReference configuration={configuration} />
        </div>
    </>
    
  )
}
```

**Comment by hanspagel** [comment] 2023-11-27 10:32
As a side note: Next.js 13 seems to work just fine.

**Comment by Gertjan1996** [comment] 2023-12-15 12:36
I also have some issues setting this up inside Next.js.

The @scalar/api-reference import results in type checking with Vue types instead of React types, which results in build time errors. Using 'use client' makes sure that the application at least builds. Both frameworks use the global jsx to add their typings and apparently, Vue types win. Tried some workarounds with patch-package and changing the tsconfig.json, but didn't find a working solution yet. This is the same reason as to why I have to use `@ts-ignore` (otherwise, I'll have the following error: `Vue: Type Element  is not assignable to type  ReactNode Type  Element  is not assignable to type  ReactPortal`).

The following code does build and the production build actually works, but with the dev build, the html only renders `<div data-use-vue-component-wrap="" style="all:unset" data-v-app=""></div>` without the inner html.

So, it seems like this setup will work in production, but without a working dev environment and with having to use `use client` and `@ts-ignore`, it's of course far from ideal currently

```
'use client'
import { ApiReference as VueComponent } from '@scalar/api-reference'
import { applyVueInReact } from 'veaury'

const ApiReference = applyVueInReact(VueComponent)

export default function Page() {
  return (
    <div>
      { /** @ts-ignore */ }
      <ApiReference configuration={{ isEditable: true }} />
    </div>
  )
}
```

```
  "dependencies": {
    "@scalar/api-reference": "^1.10.2",
    "next": "14.0.4",
    "react": "^18",
    "react-dom": "^18",
    "sass": "^1.69.5",
    "veaury": "^2.3.12"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.0.4",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
```

**Comment by iqfareez** [comment] 2023-12-28 12:41
Yeah, I'm having the same issue with Next JS 14. Code below works in development but failed to build for production.

```js
import { ApiReference as VueComponent } from '@scalar/api-reference'
import { applyVueInReact } from 'veaury'

const ApiReference = applyVueInReact(VueComponent) as any

export default function App() {
    const configuration = {
        spec: {
            url: 'https://raw.githubusercontent.com/mptwaktusolat/open-api-spec/main/mpt-server-api.yaml'
        }
    };
    
    return (
        <>
            {/* @ts-ignore */}
            <ApiReference configuration={configuration} />
        </>
    )
}
```

When run `yarn build`. I got this error

```
Type error: 'Component' cannot be used as a JSX component.
  Its element type 'Component<any, any, any> | ReactElement<any, any>' is not a valid JSX element.
    Type 'Component<any, any, any>' is not assignable to type 'Element | ElementClass'.
      Property '$props' is missing in type 'Component<any, any, any>' but required in type 'ElementClass'.
```

Try whole bunch of solution in StackOverflow but didn't find any solution. I think the issue is related to types, just like @Gertjan1996 have mentioned above.

**Comment by hanspagel** [comment] 2024-01-25 11:32
Say hello to our new Next.js package: https://www.npmjs.com/package/@scalar/nextjs-api-reference

😊

**Comment by totaland** [comment] 2024-02-19 01:51
What if I don't want to use api route?

**Comment by marclave** [comment] 2024-02-19 02:01
@totaland we agree on this and we are working on this : ) @amritk is there another ticket or should we re-open this ticket?

**Comment by totaland** [comment] 2024-02-19 02:33
Can you reopen this ticket please?

**Comment by marclave** [comment] 2024-02-19 03:57
yeah let's re open it :)

**Comment by amritk** [comment] 2024-03-13 00:47
Hello all, we can now use the [@scalar/api-reference-react](https://www.npmjs.com/package/@scalar/api-reference-react) package in the client in the latest version of next.js (14.1.3). I am updating the example right now but you can try:
```tsx
'use client'

import { ApiReferenceReact } from '@scalar/api-reference-react'
import React from 'react'

export const ClientWrapper = () => (
  <ApiReferenceReact
    configuration={{
      spec: {
        url: 'https://petstore.swagger.io/v2/swagger.json',
      },
    }}
  />
)
```

Currently it mounts on the client side only. We still need to do a bit more work to get a true server side rendered vue app that mounts correctly.

**Comment by amritk** [comment] 2024-10-30 23:21
I will close this ticket as we having working examples for next.js and will make an integration soon!

**Closed by amritk** 2024-10-30 23:21 UTC
Labels: bug, help wanted, package: @scalar/nextjs-api-reference
