### ISSUE TITLE
The problem of the default listening address of.Net9 WebAPI

### ISSUE THREAD

**Issue by zhongbiran** [scalar/scalar#4082] opened 2024-12-04 07:31 UTC
### What happens?

Previously, I defaulted to using urls in appsetting.json as listening, but in the UI it became [::]:9001. Using seed also indicated cross-domain issues. The same SwaggerUI does not have this problem.

### What did you expect to happen?

To solve the problem, I used the following code：
```
var webUrl = config.GetValue<string>("Urls");
builder.WebHost.UseUrls(Regex.Replace(webUrl, "\\*", "localhost"),webUrl);
```
plesase don't let them happen again

**Comment by xC0dex** [comment] 2024-12-04 17:40
Hi,

I’m not entirely sure I understand the issue you're describing. Scalar relies on the generated OpenAPI document and uses the server information provided within it. The document generator in `Microsoft.AspNetCore.OpenApi` uses the [`IServerAddressesFeature`](https://github.com/dotnet/aspnetcore/blob/main/src/OpenApi/src/Services/OpenApiDocumentService.cs#L198) feature. Perhaps the values from this aren't being generated as expected.

**Comment by tom-englert** [comment] 2024-12-13 11:05
I had the same problem, but it only happens in development environment:

`appsettings.json`:
```json
  "Kestrel": {
    "Endpoints": {
      "Default": {
        "Url": "http://+:8080"
      }
    }
  },
  "AllowedHosts": "*"
```

`launchsettings.json`:
```json
"environmentVariables": {
  "ASPNETCORE_ENVIRONMENT": "Development",
  "SystemLog__MinimumLevel__Default": "Debug"
},
```

**Fix:**
`launchsettings.json`:
```json
"environmentVariables": {
  "ASPNETCORE_ENVIRONMENT": "Development",
  "Kestrel__Endpoints__Default__Url": "http://localhost:8080",
  "SystemLog__MinimumLevel__Default": "Debug"
},
```

**Comment by xC0dex** [comment] 2024-12-13 11:39
> but it only happens in development environment:

Yes. The link I shared in the previous comment refers to the implementation in the `Microsoft.AspNetCore.OpenApi` package. There is the condition `hostEnvironment.IsDevelopment()`.

This is not an issue in the `Scalar.AspNetCore` package.

**Comment by tom-englert** [comment] 2024-12-16 14:09
![image](https://github.com/user-attachments/assets/d968881c-aae2-45b9-b23a-171fa101fdcb)
This is an invalid address, so trying to test this request fails.

**Comment by xC0dex** [comment] 2024-12-17 09:15
I believe this still seems more like a feature than a bug. `SwaggerUI` behaves the same way.

![image](https://github.com/user-attachments/assets/a0643def-1f07-46b1-a323-70ecf4b26866)

If a `server` key is defined in the OpenAPI document, it will be used as the base URL. IMO, the root cause lies with the `Microsoft.AspNetCore.OpenApi` document generator. Unlike `Swashbuckle` or `NSwag`, which rely on `HttpContext` to dynamically generate the server URL, this generator uses the [IServerAddressesFeature](https://github.com/dotnet/aspnetcore/blob/main/src/OpenApi/src/Services/OpenApiDocumentService.cs#L198) feature. There are some similar issues reported in the AspNetCore repo: https://github.com/dotnet/aspnetcore/issues/59313 and https://github.com/dotnet/aspnetcore/issues/57332.

**Comment by tom-englert** [comment] 2024-12-19 09:42
I agree that, looking at the OpenAPI schema documentation, Microsoft seems to be wrong.

The best workaround seems to be the custom document transformer that clears the servers entries to prevent the invalid server entry.

**Comment by xC0dex** [comment] 2024-12-22 20:02
I'll close this issue because the bug itself is not `Scalar.AspNetCore` related. I think with .NET 10 they will address this issue, so I recommend keeping an eye on this issue https://github.com/dotnet/aspnetcore/issues/57332.

**Closed by xC0dex** 2024-12-22 20:02 UTC
Labels: bug
