### ISSUE TITLE
Mobile header is shown

### ISSUE THREAD

**Issue by olegsavelos** [scalar/scalar#3195] opened 2024-09-23 08:03 UTC
### What happens?

In the latest build 1.2.4 mobile header is shown and some other artifacts are present, apart form the inconsistency its impossible to execute api search.

This happens in MS Edge.

![image](https://github.com/user-attachments/assets/b2943607-a795-44bf-9395-b9db0e9d0307)

Everything seem to be working as expected in mobile browser.

### What did you expect to happen?

Mobile header to be only shown on mobile devices.

Edit

Similar to #3166

**Comment by xC0dex** [comment] 2024-09-23 11:01
I'll check that later. I'm not sure if it's a bug in the `Scalar.AspNetCore` package or in the latest referenced Api Reference.

**Comment by xC0dex** [comment] 2024-09-23 17:15
Okay, I was able to reproduce the described issue when using the api-reference with plain HTML. Seems to be the same behavior as in already related issue #3166.

**Comment by hanspagel** [comment] 2024-09-24 08:41
Not related to the integration, it’s in the sandbox, too:

<img width="763" alt="Screenshot 2024-09-24 at 10 40 54" src="https://github.com/user-attachments/assets/1ef4c000-53fd-4294-b53e-13b992ed459e">

https://sandbox.scalar.com/e/7DXfN

**Comment by hanspagel** [comment] 2024-09-24 08:58
This looks related:

Looks like the sidebar has some issues

Next.js: https://scalar-example-next-js-p6gnzjpyuq-uc.a.run.app/

https://github.com/user-attachments/assets/d50805b0-f33f-4cbf-b445-d93d9905d9b8

**Comment by hanspagel** [comment] 2024-09-25 08:24
Hono

<img width="312" alt="Screenshot 2024-09-25 at 10 24 21" src="https://github.com/user-attachments/assets/c41e5287-d683-4ae5-b522-e4fbbce5524b">

**Comment by hwkr** [comment] 2024-09-26 20:45
Should be fixed in #3253

**Closed by hwkr** 2024-09-26 20:45 UTC
Labels: bug, package: @scalar/api-reference
