### ISSUE TITLE
Read properties of undefined 'uid'

### ISSUE THREAD

**Issue by peplxx** [scalar/scalar#4169] opened 2024-12-11 23:14 UTC
## Problem

Hello, I tried to add Scalar to my FastAPI template and encountered the following error:

![Error Screenshot](https://github.com/user-attachments/assets/c4f286c1-9066-4e23-a90c-8b866c3add29)

This error is shown in the description of all endpoints.

### What I have tried to fix

1. I thought that my auth module might have incorrect hints for OpenAPI related to UUIDs, so I disabled them. However, the same error still occurs.
2. I analyzed the `openapi.json` file but did not find any UUID-related fields.

### Toy Example

To test if Scalar integration works or not, I created a minimal example:

```python
from fastapi import FastAPI
import uvicorn
from scalar_fastapi import get_scalar_api_reference

app = FastAPI()

@app.get("/")
def hello():
    return {"message": "Hello World!"}

@app.get("/scalar", include_in_schema=False)
async def scalar_html():
    return get_scalar_api_reference(
        openapi_url=app.openapi_url,
        title=app.title,
    )

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=5000)
```

However, this toy example also reproduces the error, and I’m unsure how to resolve it:
![image](https://github.com/user-attachments/assets/f6131f07-e433-4bd2-aa71-080e81870bbc)
## Version Information

- `scalar-fastapi == 1.0.3`
- `Ubuntu 22.04`

## OpenAPI Links
- [Reduced Template's OpenAPI](https://sandbox.scalar.com/e/nAucc)
- [Toy example's OpenAPI](https://sandbox.scalar.com/e/TbI5N)

### What did you expect to happen?

I expect Scalar to work :)

### OpenAPI Document

https://sandbox.scalar.com/e/nAucc

**Comment by utrolig** [comment] 2024-12-11 23:25
I have the same issue, but downgrading to the previous patch version made it working again..
I'm using `@scalar/fastify-api-reference` with version `1.25.78` while `1.25.79` doesn't work. I don't know how the python packages are managed though.

**Comment by merkdev** [comment] 2024-12-11 23:40
I have 2 apps. One have issue and other one works well. Very weird.

Issue with nodejs nextjs hono stack
No issue with nodejs hono stack

**Comment by utrolig** [comment] 2024-12-11 23:42
> I have 2 apps. One have same issue and other one works well. Very weird.
> 
> Issue with nodejs nextjs hono stack No issue with nodejs hono stack

They might be using different versions of the package. Check your lockfiles

**Comment by peplxx** [comment] 2024-12-11 23:47
I think there is some problem in latest version btw, in sandbox it also not working.

You can check your openapi.json sandbox, I apologize it uses latest version of Scalar.
https://sandbox.scalar.com

**Comment by utrolig** [comment] 2024-12-11 23:48
Yeah it looks like there's already a [PR](https://github.com/scalar/scalar/pull/4171/files) opened for it.

**Comment by merkdev** [comment] 2024-12-11 23:50
@utrolig downgrading didn't help. 0.5.163 -> 0.5.156

Btw. Supabase v1 API Reference has same issue too;
https://api.supabase.com/api/v1

**Comment by merkdev** [comment] 2024-12-12 00:05
For anyone who need quick fix; Adding server fixed the issue.

servers: [{url: "/"}]

**Comment by antlio** [comment] 2024-12-12 07:52
sorry about that, thank you all for the report, a fix has been deployed see #4170 &
another PR has been open to make sure we avoid this in the future in #4171

**Comment by Davispc10** [comment] 2024-12-12 13:09
I'm using the @elysiajs/swagger lib and it still has the uid error.

![image](https://github.com/user-attachments/assets/e01a28e2-f228-4e41-ac1d-e081283d0bbe)

**Comment by antlio** [comment] 2024-12-12 13:54
> I'm using the @elysiajs/swagger lib and it still has the uid error.
> 

hey @Davispc10 sorry about this, do you use any version within the lib? I just purged the cdn, is the issue remain?

**Comment by Davispc10** [comment] 2024-12-12 14:06
I think they need to update the lib @elysiajs/swagger, because it's using old @scalar/types version.

![image](https://github.com/user-attachments/assets/f99398a5-7ea6-4b5e-ae3c-1055cf4eb41d)

**Comment by antlio** [comment] 2024-12-12 14:21
as the issue was in the api-reference package that has been updated and elysiajs/swagger using its cdn i would have think it's fixed also there - will keep digging! cc @marclave

**Comment by gabs-passarinho-garcia** [comment] 2024-12-12 15:24
I'm having the same issue with @elysiajs/swagger, I have update the package but it didn't solve the problem. It is very strange because on my local execution (docker and native) it works fine, but on my server on AWS, using the same docker image, the issue is happening

**Comment by antlio** [comment] 2024-12-12 16:11
@gabs-passarinho-garcia do you mind sharing your specification or something similar within https://sandbox.scalar.com/?

**Comment by gabs-passarinho-garcia** [comment] 2024-12-12 16:18
> @gabs-passarinho-garcia do you mind sharing your specification or something similar within https://sandbox.scalar.com/?

![image](https://github.com/user-attachments/assets/2e3457ed-7602-4a9a-84af-6dffebf3ed9e)
I added my open-api json to the sandbox and it worked just fine

**Comment by gabs-passarinho-garcia** [comment] 2024-12-13 02:20
I've checked and it's working now, so thanks for your help.

**Comment by antlio** [comment] 2024-12-13 07:39
@gabs-passarinho-garcia great to hear, closing this as for now - feel free to reach out if you need anything!

**Closed by antlio** 2024-12-13 07:39 UTC
Labels: bug, package: @scalar/api-reference
